main: main.o Personas.o Clientes.o Repartidores.o Empleados.o Ordenes.o Negocio.o Productos.o
	g++ main.o Personas.o Clientes.o Repartidores.o Empleados.o Ordenes.o Negocio.o Productos.o -o Hugo
main.o: main.cpp
	g++ -c main.cpp
Personas.o: Personas.cpp Personas.h 
	g++ -c Personas.cpp
Clientes.o: Clientes.cpp Clientes.h 
	g++ -c Clientes.cpp
Repartidores.o: Repartidores.cpp Repartidores.h 
	g++ -c Repartidores.cpp
Empleados.o: Empleados.cpp Empleados.h 
	g++ -c Empleados.cpp
Ordenes.o: Ordenes.cpp Ordenes.h 
	g++ -c Ordenes.cpp
Negocio.o: Negocio.cpp Negocio.h 
	g++ -c Negocio.cpp
Productos.o: Productos.cpp Productos.h 
	g++ -c Productos.cpp